version: '3.2'
services:
  app:
    image: http_reflectJS:{tag}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.frontend.rule=Host:{yourhost.com}
        - traefik.port=3000
        - traefik.docker.network=http_network
    networks:
      - http_network

networks:
  http_network:
    external: true